import React, { ReactNode } from 'react'
import StreamVideoProvider from '../../../providers/StreamClientProvider'
import { Metadata } from 'next';

export const metadata: Metadata = {
  title: "ConnectSpace",
  description: "Generated by ConnectSpace",
  icons:{
    icon: '/icons/logo.svg'
  }
};


const RootLayout = ({children}:{children:ReactNode}/**childeren is a react props using typescript*/) => {
  return (
    <main>
      <StreamVideoProvider>
        {children}
      </StreamVideoProvider>
    </main>
  )
}

export default RootLayout
