import React, { Children, ReactNode } from 'react'

import Navbar from '@/components/Navbar'
import Sidebar from '@/components/Sidebar'
import { Metadata } from 'next';

export const metadata: Metadata = {
  title: "ConnectSpace",
  description: "Generated by ConnectSpace",
  icons:{
    icon: '/icons/logo.svg'
  }
};

const HomeLayout = ({children}:{children:ReactNode}/**childeren is a react props using typescript*/) => {
  return (
    <main className='relative'>
        <Navbar />
  
        <div className=' flex'>
            <Sidebar />
            <section className=' flex min-h-screen flex-1 flex-col px-6 pb-6 pt-28 max-md:pb-14 sm:px-14'>
                <div className=' w-full'></div>
                {children}
            </section>
        </div>
    </main>
  )
}

export default HomeLayout
